name: Docker

on:
  push:
    branches: [main]

jobs:
  build-push:
    permissions:
      contents: read
      packages: write
    uses: noahkiss/workflows/.github/workflows/ghcr-build-push.yml@main
